dist: trusty
language: python

before_install:
  - openssl aes-256-cbc -K $encrypted_be90c687bd7a_key -iv $encrypted_be90c687bd7a_iv -in .github/deploy_key.enc -out deploy_key -d

python:
  - "2.7"

env:
  global:
    # !!! Replace the encryption label below with YOURS generated
    - ENCRYPTION_LABEL: "be90c687bd7a"
    # !!! Replace the email below with YOURS
    - COMMIT_AUTHOR_EMAIL: "tvhk.master@gmail.com"

script:
  - bash .github/build.sh

branches:
  only:
    - master
    # Add more branches if required
